### PR TITLE
add i18n and translate to ptBR

### PR DESCRIPTION
**Pull request by tiagoceridorio**

### CODE REVIEW

**Review by PoloBustillo — APPROVED** [review]

**Review by mvarchdev — APPROVED** [review]
Very nice work! As followup there would be good to also add translations for each independent collection fields etc. I had smth prepared with using firestore but it was only on top. Also, is there some option to provide customised translations? Like externally, without changing the lib directly

**Comment by mvarchdev** [comment]
@fgatti675 hello! What is the state of this PR? Will it be merged? Thanks in advance!

**Comment by mvarchdev** [comment]
@tiagoceridorio hey - Is there possibility to add localisation support for collections also? Thanks in advance

**Comment by fgatti675** [comment]
Hi guys, I need to close this PR since it was meant for V2, for which we have stopped development.
All new features will be implemented in V3, which has changed dramatically

**Comment by Alynva** [comment]
I miss be able to translate the CMS interface

**Pull request closed without merging**
